---
title: "New Zealand Police Shootings"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme:
      version: 4
      bootswatch: cerulean
    social: ["twitter", "linkedin"]
    source_code: 'https://github.com/dataforyounz/nz-police-shootings/tree/main'
---

```{r setup, include=FALSE}
library( flexdashboard )
library( dplyr )
library( DT )
library( leaflet )
library( highcharter )
library( htmltools )

data_folder <- "dat"
data_file   <- "shooting_data_clean.Rdata"
data_path   <- file.path( data_folder, data_file )

# Load shooting data
load( data_path )

data_file   <- "geo_data.Rdata" 
data_path   <- file.path( data_folder, data_file )

load( data_path )

pal <- colorNumeric(
  palette = "Blues",
  domain = district_geo_data$Count
  )

label_content <- lapply( seq_along(district_geo_data$District), 
                         function(x){
                            HTML( paste0( strong("District: "), 
                                          district_geo_data$District[x] ), 
                                 '<hr style="height:1px;border-width:0;color:gray;background-color:gray">',
                                  paste0( strong("Fatal: "), 
                                         district_geo_data$total_fatal[x] ),
                                 "<br>",
                                  paste0( strong("Non-Fatal: "), 
                                         district_geo_data$total_non_fatal[x] ),
                                 "<br>",
                                  paste0( strong("Misses: "), 
                                         district_geo_data$total_miss[x] ),
                                 '<hr style="height:1px;border-width:0;color:gray;background-color:gray">',
                                  paste0( strong("Total: "), 
                                          district_geo_data$Count[x] )
                                 )
})

```

About
===================================================================

#### About this dashbaord

---

Visualises data about police shootings between 1916 – 2021

Link to data 

Last updated: `r format(Sys.Date(), "%d/%m/%Y")`

---

Shootings 
===================================================================

Row
--------------------------------- 

### 

```{r }
flexdashboard::valueBox( value = total_shootings, 
                         caption = "Total Police Shootings", 
                         icon = "fa-info")
```

###

```{r}
flexdashboard::valueBox( value = total_fatal, 
                         caption = "Total Fatal Shootings",
                         icon = "fa-info")
```

###

```{r}
flexdashboard::valueBox( value = total_non_fatal, 
                         caption = "Total Non-Fatal Shootings",
                         icon = "fa-info" )
```

###

```{r}
flexdashboard::valueBox( value = total_miss, 
                         caption = "Total Shots Missed",
                         icon = "fa-info" )
```


Row
--------------------------------- 

### Shootings by Police District

```{r}

leaflet(district_geo_data) %>% 
  addTiles() %>% 
  addPolygons( weight = 1, smoothFactor = 0.5, opacity = 1.0, 
               fillOpacity = 0.5, color = ~pal(Count),
               label = ~label_content,
               fillColor = ~pal(Count),
               highlightOptions = highlightOptions(color = "white", weight = 2,
                                                   bringToFront = TRUE),
               labelOptions = labelOptions(
                 style = list( "background-color" = "skyblue" )
               )
               )
  

```

### Number of Police Shootings per Year

```{r}

hchart( shootings_by_year, "column", 
        hcaes(x = Year, y = Count, group = Outcome) ) %>% 
  #hc_title(text = "Number of Police Shootings per Year") %>% 
  hc_plotOptions( column = list(stacking = "normal" )) %>% 
  hc_yAxis( title = list(text = "Number of Shootings") )

```

> Source: New Zealand Police

Data 
===================================================================

##### Use the buttons below to export the data

### 

```{r}

datatable( shooting_df )

```

